FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim AS builder

ADD . /app
WORKDIR /app
RUN uv sync --no-dev

FROM python:3.13-slim-bookworm

WORKDIR /app
COPY --from=builder /app /app

ENV PYTHONPATH=/app/src

CMD ["/app/.venv/bin/python", "src/{{project_slug_underscore}}/main.py"]